services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrack
    ports:
      - "5432:5432"
    volumes:
      - fintrack_db:/var/lib/postgresql/data

volumes:
  fintrack_db:
